name: CD-Pipeline

on:
  schedule: # every hour
    - cron: 0 */3 * * *

permissions:
  contents: write

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  Deploy:
    # Rust is preconfigured on the ubuntu-latest runner
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Build App
        run: cargo build --release
      
      - name: Run App
        run: |
          args_list=("--rust" "--typescript" "--react" "--machine learning" "--typescript react" "--typescript express")
          for arg in "${args_list[@]}"; do
            ./target/release/rusty-backend "$arg"
          done