name: CD-Pipeline

on:
  schedule:
    - cron: 0,30 */3 * * *

permissions:
  contents: write

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Build App
        run: cargo build --release

      - name: Run App
        run: |
          args_list=("rust" "typescript" "react" "machine learning" "typescript react" "typescript express")
          for arg in "${args_list[@]}"; do
            ./target/release/rusty-backend -- "$arg"
          done

      - name: Commit changes
        id: commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Actions database update" -a
          
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main